In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('Data.csv')

In [17]:
pd.set_option('display.max_columns', 100)

In [18]:
df.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Item_Outlet_Sales,Item_Outlet_Sales_BOXCOX,Item_Fat_Content_Regular,Item_Type_Group2,Item_Type_Group3,Item_Type_Group4,Item_Type_Group5,Outlet_Identifier_OUT013,Outlet_Identifier_OUT017,Outlet_Identifier_OUT018,Outlet_Identifier_OUT019,Outlet_Identifier_OUT027,Outlet_Identifier_OUT035,Outlet_Identifier_OUT045,Outlet_Identifier_OUT046,Outlet_Identifier_OUT049,Outlet_Establishment_Year_1987,Outlet_Establishment_Year_1997,Outlet_Establishment_Year_1998,Outlet_Establishment_Year_1999,Outlet_Establishment_Year_2002,Outlet_Establishment_Year_2004,Outlet_Establishment_Year_2007,Outlet_Establishment_Year_2009,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_Visibility_SQRT
0,9.30000,0.016047,249.8092,2,3,3735.1380,59.004256,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0.126678
1,5.92000,0.019278,48.2692,2,1,443.4228,24.528125,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0.138846
2,17.50000,0.016760,141.6180,2,3,2097.2700,46.733445,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0.129461
3,13.65000,0.012741,57.6588,3,1,343.5528,21.990538,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0.112876
4,11.94125,0.127470,107.7622,2,1,4022.7636,60.788510,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.357029

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7817 entries, 0 to 7816
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Item_Weight                     7817 non-null   float64
 1   Item_Visibility                 7817 non-null   float64
 2   Item_MRP                        7817 non-null   float64
 3   Outlet_Size                     7817 non-null   int64
 4   Outlet_Location_Type            7817 non-null   int64
 5   Item_Outlet_Sales               7817 non-null   float64
 6   Item_Outlet_Sales_BOXCOX        7817 non-null   float64
 7   Item_Fat_Content_Regular        7817 non-null   int64
 8   Item_Type_Group2                7817 non-null   int64
 9   Item_Type_Group3                7817 non-null   int64
 10  Item_Type_Group4                7817 non-null   int64
 11  Item_Type_Group5                7817 non-null   int64
 12  Outlet_Identifier_OUT013        7817 non-null   int64
 13  Outlet_Identifier_OUT017        7817 non-null   int64
 14  Outlet_Identifier_OUT018        7817 non-null   int64
 15  Outlet_Identifier_OUT019        7817 non-null   int64
 16  Outlet_Identifier_OUT027        7817 non-null   int64
 17  Outlet_Identifier_OUT035        7817 non-null   int64
 18  Outlet_Identifier_OUT045        7817 non-null   int64
 19  Outlet_Identifier_OUT046        7817 non-null   int64
 20  Outlet_Identifier_OUT049        7817 non-null   int64
 21  Outlet_Establishment_Year_1987  7817 non-null   int64
 22  Outlet_Establishment_Year_1997  7817 non-null   int64
 23  Outlet_Establishment_Year_1998  7817 non-null   int64
 24  Outlet_Establishment_Year_1999  7817 non-null   int64
 25  Outlet_Establishment_Year_2002  7817 non-null   int64
 26  Outlet_Establishment_Year_2004  7817 non-null   int64
 27  Outlet_Establishment_Year_2007  7817 non-null   int64
 28  Outlet_Establishment_Year_2009  7817 non-null   int64
 29  Outlet_Type_Supermarket Type1   7817 non-null   int64
 30  Outlet_Type_Supermarket Type2   7817 non-null   int64
 31  Outlet_Type_Supermarket Type3   7817 non-null   int64
 32  Item_Visibility_SQRT            7817 non-null   float64
dtypes: float64(6), int64(27)
memory usage: 2.0 MB

In [15]:
from scipy import stats
from scipy.special import boxcox, inv_boxcox

In [26]:
df['Item_Outlet_Sales_Boxcox'],parameters=stats.boxcox(df['Item_Outlet_Sales'])

In [27]:
parameters

0.3854186331879921

In [28]:
df['Item_Outlet_Sales_Inv_Boxcox']=inv_boxcox(df['Item_Outlet_Sales_Boxcox'],0.3854186331879921)

In [33]:
df.drop(columns=['Item_Outlet_Sales','Item_Outlet_Sales_Boxcox','Item_Outlet_Sales_Inv_Boxcox'],inplace=True)

### ML

In [5]:
df

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Item_Outlet_Sales,Item_Outlet_Sales_BOXCOX,Item_Fat_Content_Regular,Item_Type_Group2,Item_Type_Group3,...,Outlet_Establishment_Year_1998,Outlet_Establishment_Year_1999,Outlet_Establishment_Year_2002,Outlet_Establishment_Year_2004,Outlet_Establishment_Year_2007,Outlet_Establishment_Year_2009,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_Visibility_SQRT
0,9.30000,0.016047,249.8092,2,3,3735.1380,59.004256,0,1,0,...,0,1,0,0,0,0,1,0,0,0.126678
1,5.92000,0.019278,48.2692,2,1,443.4228,24.528125,1,0,0,...,0,0,0,0,0,1,0,1,0,0.138846
2,17.50000,0.016760,141.6180,2,3,2097.2700,46.733445,0,0,1,...,0,1,0,0,0,0,1,0,0,0.129461
3,13.65000,0.012741,57.6588,3,1,343.5528,21.990538,1,0,0,...,0,0,0,0,0,0,1,0,0,0.112876
4,11.94125,0.127470,107.7622,2,1,4022.7636,60.788510,0,0,0,...,0,0,0,0,0,0,0,0,1,0.357029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,6.86500,0.056783,214.5218,3,1,2778.3834,52.372930,0,0,0,...,0,0,0,0,0,0,1,0,0,0.238293
7813,8.38000,0.046982,108.1570,3,2,549.2850,26.858052,1,0,0,...,0,0,1,0,0,0,1,0,0,0.216754
7814,10.60000,0.035186,85.1224,1,2,1193.1136,37.106254,0,0,0,...,0,0,0,1,0,0,1,0,0,0.187580
7815,7.21000,0.145221,103.1332,2,1,1845.5976,44.365011,1,0,0,...,0,0,0,0,0,1,0,1,0,0.381078
7816,14.80000,0.044878,75.4670,1,3,765.6700,30.874816,0,0,0,...,0,0,0,0,0,0,1,0,0,0.211845

In [62]:
X=df.drop(['Item_Outlet_Sales',
           'Item_Outlet_Sales_BOXCOX',
           'Item_Visibility_SQRT',
           'Outlet_Identifier_OUT013',
           'Outlet_Identifier_OUT017',
           'Outlet_Identifier_OUT018',
           'Outlet_Identifier_OUT019',
           'Outlet_Identifier_OUT027',
           'Outlet_Identifier_OUT035',
           'Outlet_Identifier_OUT045',
           'Outlet_Identifier_OUT046',
           'Outlet_Identifier_OUT049',
           'Outlet_Establishment_Year_1987',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_1998',
           'Outlet_Establishment_Year_1999',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_2002',
           'Outlet_Establishment_Year_2004',
           'Outlet_Establishment_Year_2007',
           'Outlet_Establishment_Year_2009',
          ],axis=1)
y=df['Item_Outlet_Sales'].reset_index(drop=True)

In [64]:
adat=df.drop([
           'Item_Outlet_Sales_BOXCOX',
           'Item_Visibility_SQRT',
           'Outlet_Identifier_OUT013',
           'Outlet_Identifier_OUT017',
           'Outlet_Identifier_OUT018',
           'Outlet_Identifier_OUT019',
           'Outlet_Identifier_OUT027',
           'Outlet_Identifier_OUT035',
           'Outlet_Identifier_OUT045',
           'Outlet_Identifier_OUT046',
           'Outlet_Identifier_OUT049',
           'Outlet_Establishment_Year_1987',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_1998',
           'Outlet_Establishment_Year_1999',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_2002',
           'Outlet_Establishment_Year_2004',
           'Outlet_Establishment_Year_2007',
           'Outlet_Establishment_Year_2009',
          ],axis=1)

In [65]:
adat

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Item_Outlet_Sales,Item_Fat_Content_Regular,Item_Type_Group2,Item_Type_Group3,Item_Type_Group4,Item_Type_Group5,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30000,0.016047,249.8092,2,3,3735.1380,0,1,0,0,0,1,0,0
1,5.92000,0.019278,48.2692,2,1,443.4228,1,0,0,1,0,0,1,0
2,17.50000,0.016760,141.6180,2,3,2097.2700,0,0,1,0,0,1,0,0
3,13.65000,0.012741,57.6588,3,1,343.5528,1,0,0,1,0,1,0,0
4,11.94125,0.127470,107.7622,2,1,4022.7636,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,6.86500,0.056783,214.5218,3,1,2778.3834,0,0,0,1,0,1,0,0
7813,8.38000,0.046982,108.1570,3,2,549.2850,1,0,0,0,0,1,0,0
7814,10.60000,0.035186,85.1224,1,2,1193.1136,0,0,0,0,1,1,0,0
7815,7.21000,0.145221,103.1332,2,1,1845.5976,1,0,0,1,0,0,1,0
7816,14.80000,0.044878,75.4670,1,3,765.6700,0,0,0,1,0,1,0,0

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15,random_state=2)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score,mean_absolute_error

from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor,ExtraTreesRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

In [34]:
cat=df.select_dtypes(object).columns
cat

Index([], dtype='object')

In [35]:
total=0
for i in cat:
    total+=len(df[i].unique())
    print(i,f'has {len(df[i].unique())} labels :: {df[i].unique()}')
    print()
    print()
total-=len(cat)
print(f'total one hot encoded variables are {total}')

total one hot encoded variables are 0

In [46]:
df['Outlet_Establishment_Year'].unique()

array(['1999', '2009', '1987', '1985', '2002', '2007', '1997', '2004',
       '1998'], dtype=object)

### Linear Regressor

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
scaler = StandardScaler()

In [67]:
df_scaled = pd.DataFrame(scaler.fit_transform(adat),columns = adat.columns)

In [68]:
df_scaled

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Item_Outlet_Sales,Item_Fat_Content_Regular,Item_Type_Group2,Item_Type_Group3,Item_Type_Group4,Item_Type_Group5,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,-0.803236,-1.137894,1.771457,0.338578,1.369608,1.015629,-0.736494,1.699153,-0.248604,-0.526581,-0.484477,0.708396,-0.352280,-0.342335
1,-1.595282,-1.067453,-1.487830,0.338578,-1.100394,-1.070881,1.357785,-0.588529,-0.248604,1.899043,-0.484477,-1.411639,2.838651,-0.342335
2,1.118293,-1.122354,0.021799,0.338578,1.369608,-0.022561,-0.736494,-0.588529,4.022464,-0.526581,-0.484477,0.708396,-0.352280,-0.342335
3,0.216112,-1.209976,-1.335982,1.774639,-1.100394,-1.134185,1.357785,-0.588529,-0.248604,1.899043,-0.484477,0.708396,-0.352280,-0.342335
4,-0.184305,1.291352,-0.525714,0.338578,-1.100394,1.197945,-0.736494,-0.588529,-0.248604,1.899043,-0.484477,-1.411639,-0.352280,2.921117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,-1.373837,-0.249761,1.200793,1.774639,-1.100394,0.409174,-0.736494,-0.588529,-0.248604,1.899043,-0.484477,0.708396,-0.352280,-0.342335
7813,-1.018823,-0.463443,-0.519330,1.774639,0.134607,-1.003778,1.357785,-0.588529,-0.248604,-0.526581,-0.484477,0.708396,-0.352280,-0.342335
7814,-0.498604,-0.720624,-0.891843,-1.097484,0.134607,-0.595676,-0.736494,-0.588529,-0.248604,-0.526581,2.064081,0.708396,-0.352280,-0.342335
7815,-1.292992,1.678356,-0.600574,0.338578,-1.100394,-0.182088,1.357785,-0.588529,-0.248604,1.899043,-0.484477,-1.411639,2.838651,-0.342335
7816,0.485594,-0.509318,-1.047990,-1.097484,1.369608,-0.866619,-0.736494,-0.588529,-0.248604,1.899043,-0.484477,0.708396,-0.352280,-0.342335

In [69]:
X=adat.drop(['Item_Outlet_Sales',
           'Item_Outlet_Sales_BOXCOX',
           'Item_Visibility_SQRT',
           'Outlet_Identifier_OUT013',
           'Outlet_Identifier_OUT017',
           'Outlet_Identifier_OUT018',
           'Outlet_Identifier_OUT019',
           'Outlet_Identifier_OUT027',
           'Outlet_Identifier_OUT035',
           'Outlet_Identifier_OUT045',
           'Outlet_Identifier_OUT046',
           'Outlet_Identifier_OUT049',
           'Outlet_Establishment_Year_1987',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_1998',
           'Outlet_Establishment_Year_1999',
           'Outlet_Establishment_Year_1997',
           'Outlet_Establishment_Year_2002',
           'Outlet_Establishment_Year_2004',
           'Outlet_Establishment_Year_2007',
           'Outlet_Establishment_Year_2009',
          ],axis=1)
y=adat['Item_Outlet_Sales'].reset_index(drop=True)

KeyError: "['Item_Outlet_Sales_BOXCOX', 'Item_Visibility_SQRT', 'Outlet_Identifier_OUT013', 'Outlet_Identifier_OUT017', 'Outlet_Identifier_OUT018', 'Outlet_Identifier_OUT019', 'Outlet_Identifier_OUT027', 'Outlet_Identifier_OUT035', 'Outlet_Identifier_OUT045', 'Outlet_Identifier_OUT046', 'Outlet_Identifier_OUT049', 'Outlet_Establishment_Year_1987', 'Outlet_Establishment_Year_1997', 'Outlet_Establishment_Year_1998', 'Outlet_Establishment_Year_1999', 'Outlet_Establishment_Year_1997', 'Outlet_Establishment_Year_2002', 'Outlet_Establishment_Year_2004', 'Outlet_Establishment_Year_2007', 'Outlet_Establishment_Year_2009'] not found in axis"

In [71]:
adat

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Item_Outlet_Sales,Item_Fat_Content_Regular,Item_Type_Group2,Item_Type_Group3,Item_Type_Group4,Item_Type_Group5,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30000,0.016047,249.8092,2,3,3735.1380,0,1,0,0,0,1,0,0
1,5.92000,0.019278,48.2692,2,1,443.4228,1,0,0,1,0,0,1,0
2,17.50000,0.016760,141.6180,2,3,2097.2700,0,0,1,0,0,1,0,0
3,13.65000,0.012741,57.6588,3,1,343.5528,1,0,0,1,0,1,0,0
4,11.94125,0.127470,107.7622,2,1,4022.7636,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,6.86500,0.056783,214.5218,3,1,2778.3834,0,0,0,1,0,1,0,0
7813,8.38000,0.046982,108.1570,3,2,549.2850,1,0,0,0,0,1,0,0
7814,10.60000,0.035186,85.1224,1,2,1193.1136,0,0,0,0,1,1,0,0
7815,7.21000,0.145221,103.1332,2,1,1845.5976,1,0,0,1,0,0,1,0
7816,14.80000,0.044878,75.4670,1,3,765.6700,0,0,0,1,0,1,0,0

In [51]:
X=scaler.fit_transform(X)

In [54]:
y=scaler.fit_transform(y)

ValueError: Expected 2D array, got 1D array instead:
array=[3735.138   443.4228 2097.27   ... 1193.1136 1845.5976  765.67  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [52]:
X

array([[-0.80323643, -1.1378935 ,  1.77145747, ...,  0.70839619,
        -0.35228005, -0.34233475],
       [-1.59528154, -1.06745278, -1.48783017, ..., -1.41163943,
         2.83865063, -0.34233475],
       [ 1.11829311, -1.12235353,  0.02179864, ...,  0.70839619,
        -0.35228005, -0.34233475],
       ...,
       [-0.4986037 , -0.72062381, -0.89184337, ...,  0.70839619,
        -0.35228005, -0.34233475],
       [-1.29299213,  1.67835637, -0.60057426, ..., -1.41163943,
         2.83865063, -0.34233475],
       [ 0.48559436, -0.50931769, -1.04798968, ...,  0.70839619,
        -0.35228005, -0.34233475]])

In [43]:
linalg=LinearRegression()
linalg.fit(X_train,y_train)
y_pred=linalg.predict(X_test)
print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.5432699642543367
MAE 790.3246960080479

In [28]:
linalg=LinearRegression()

In [29]:
linalg.fit(X_train,y_train)

LinearRegression()

In [30]:
y_pred=linalg.predict(X_test)

In [31]:
print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.5432699642543367
MAE 790.3246960080479

In [11]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = LinearRegression()

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

NameError: name 'cat' is not defined

In [51]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = Ridge(alpha=10)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6814639819472221
MAE 6.874956418193333

In [52]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = Lasso(alpha=0.001)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6819350551879255
MAE 6.872222321573811

In [53]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = KNeighborsRegressor(n_neighbors=3)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.44900364316427965
MAE 8.858632433718864

In [67]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = DecisionTreeRegressor(max_depth=8)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6760123824669328
MAE 6.847747749819685

In [28]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = SVR(kernel='rbf',C=10000,epsilon=0.1)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.7001100498317454
MAE 6.53323613022863

In [32]:
rfr=RandomForestRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15)
rfr.fit(X_train,y_train)

y_pred = rfr.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.5408814567164497
MAE 756.865416609509

In [69]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = RandomForestRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6923570695576247
MAE 6.692340211409113

In [70]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = ExtraTreesRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15,
                              bootstrap=True)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6923257478893525
MAE 6.704495644743315

In [71]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = AdaBoostRegressor(n_estimators=15,learning_rate=1.0)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6380996328208052
MAE 7.439928226867452

In [72]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = GradientBoostingRegressor(n_estimators=500)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6783623991291269
MAE 6.7960136403545395

In [73]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')

step2 = XGBRegressor(n_estimators=45,max_depth=5,learning_rate=0.5)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

R2 score 0.6606817838998534
MAE 6.9865057314717305

In [74]:
from sklearn.ensemble import VotingRegressor,StackingRegressor

step1 = ColumnTransformer(transformers=[
    ('col_tnf',OneHotEncoder(sparse=False,drop='first'),cat)
],remainder='passthrough')


rf = RandomForestRegressor(n_estimators=350,random_state=20,max_samples=0.5,max_features=0.75,max_depth=15,bootstrap=True)
gbdt = GradientBoostingRegressor(n_estimators=100,max_features=0.5)
xgb = XGBRegressor(n_estimators=25,learning_rate=0.3,max_depth=5,bootstrap=True)
et = ExtraTreesRegressor(n_estimators=100,random_state=20,max_samples=0.5,max_features=0.75,max_depth=10,bootstrap=True)

step2 = VotingRegressor([('rf', rf), ('gbdt', gbdt), ('xgb',xgb), ('et',et)],weights=[5,1,1,1])

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print('R2 score',r2_score(y_test,y_pred))
print('MAE',mean_absolute_error(y_test,y_pred))

[23:09:20] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-08de971ced8a8cdc6-1/xgboost/xgboost-ci-windows/src/learner.cc:767:
Parameters: { "bootstrap" } are not used.

R2 score 0.6985216164008239
MAE 6.603599396257407

In [29]:
df

,Item_Weight,Item_Fat_Content,Item_Type,Item_MRP,VisSqrt,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Sales_Boxcox
0,9.30000,Low Fat,Dairy,249.8092,0.126678,OUT049,1999,Medium,Tier 1,Supermarket Type1,59.192949
1,5.92000,Regular,Soft Drinks,48.2692,0.138846,OUT018,2009,Medium,Tier 3,Supermarket Type2,24.582341
2,17.50000,Low Fat,Meat,141.6180,0.129461,OUT049,1999,Medium,Tier 1,Supermarket Type1,46.870049
3,13.65000,Regular,Snack Foods,57.6588,0.112876,OUT013,1987,High,Tier 3,Supermarket Type1,22.036668
4,11.94125,Low Fat,Snack Foods,107.7622,0.357029,OUT027,1985,Medium,Tier 3,Supermarket Type3,60.985079
...,...,...,...,...,...,...,...,...,...,...,...
7811,6.86500,Low Fat,Snack Foods,214.5218,0.238293,OUT013,1987,High,Tier 3,Supermarket Type1,52.533003
7812,8.38000,Regular,Baking Goods,108.1570,0.216754,OUT045,2002,High,Tier 2,Supermarket Type1,26.919984
7813,10.60000,Low Fat,Health and Hygiene,85.1224,0.187580,OUT035,2004,Small,Tier 2,Supermarket Type1,37.204934
7814,7.21000,Regular,Snack Foods,103.1332,0.381078,OUT018,2009,Medium,Tier 3,Supermarket Type2,44.492021
7815,14.80000,Low Fat,Soft Drinks,75.4670,0.211845,OUT046,1997,Small,Tier 1,Supermarket Type1,30.950641

In [30]:
import pickle

pickle.dump(df,open('df.pkl','wb'))
pickle.dump(pipe,open('pipe.pkl','wb'))

In [22]:
type(query)

numpy.ndarray

In [23]:
query

array([['Item_Weight', 'Item_Fat_Content', 'Item_Type', 'Item_MRP',
        'VisSqrt', 'Outlet_Identifier', 'Outlet_Establishment_Year',
        'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']],
      dtype='<U25')

In [46]:
query

array(['Item_Weight', 'Item_Fat_Content', 'Item_Type', 'Item_MRP',
       'VisSqrt', 'Outlet_Identifier', 'Outlet_Establishment_Year',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type'], dtype='<U25')

In [50]:
arr=np.array([4,'Low Fat','Dairy',30,0.02,'OUT046','1997','Medium','Tier 1','Supermarket Type1'])
arr

array(['4', 'Low Fat', 'Dairy', '30', '0.02', 'OUT046', '1997', 'Medium',
       'Tier 1', 'Supermarket Type1'], dtype='<U32')

In [51]:
arr = arr.reshape(1,10)

In [52]:
arr

array([['4', 'Low Fat', 'Dairy', '30', '0.02', 'OUT046', '1997',
        'Medium', 'Tier 1', 'Supermarket Type1']], dtype='<U32')

In [54]:
pipe.predict(arr[0])

ValueError: X does not contain any features, but ColumnTransformer is expecting 10 features

In [33]:
ls=[4,'Low Fat','Dairy',30,0.02,'OUT046','1997','Medium','Tier 1','Supermarket Type1']
ls

[4,
 'Low Fat',
 'Dairy',
 30,
 0.02,
 'OUT046',
 '1997',
 'Medium',
 'Tier 1',
 'Supermarket Type1']

In [34]:
pipe.predict(ls)

ValueError: Expected 2D array, got 1D array instead:
array=[4 'Low Fat' 'Dairy' 30 0.02 'OUT046' '1997' 'Medium' 'Tier 1'
 'Supermarket Type1'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.